### ISSUE TITLE
The programmatic API was removed in npm v8.0.0

### ISSUE THREAD

**Issue by besworks** [19h/npm-adddep#2]
adddep installs but cannot work with npm v8.0.0 and above.

```
Error: The programmatic API was removed in npm v8.0.0
    at Object.<anonymous> (/usr/lib/node_modules/adddep/node_modules/npm/index.js:4:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/node_modules/adddep/add.js:4:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Comment by 19h** [comment]
@besworks thanks for letting me know.

I don't think this repo has any use anymore since you can simply use "yarn add" which does the same thing :)
